openresty:
  build: ./openresty
  ports:
    - 80:80
    - 8082:8082
    - 443:443
  links:
    - "php"
    - "redis"
  volumes:
    - /usr/local/openresty/nginx/conf:/usr/local/openresty/nginx/conf
    - /usr/local/openresty/nginx/logs:/usr/local/openresty/nginx/logs
    - /home/wwwroot:/home/wwwroot
mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
php:
  build: ./php
  ports:
    - "9000:9000"
  links:
    - "mysql"
    - "redis"
  volumes:
    - /home/wwwroot:/home/wwwroot
redis:
  build: ./redis
  ports:
    - "6379:6379"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8081:80"
  links:
    - "mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_USER: "root"
    PMA_PASSWORD: "123456"
